table 'Calendar_Full'
	lineageTag: 8e0f2a20-5140-87d9-b47b-eccdc6d4e524

	column Date
		dataType: dateTime
		isHidden
		lineageTag: b22f5137-58b4-4493-6c3e-62ffdfa18325
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		lineageTag: d02c7720-7e3b-2ef0-b8f9-c8235f944dfc
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 7fc299e2-0460-92d0-8582-8e165da6e7cf
		summarizeBy: none
		sourceColumn: Quarter

	column Month
		dataType: int64
		lineageTag: 5d1d7a86-b99d-afbd-8bf7-4297c30f0f30
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: 6aabb123-1234-5678-abcd-000000000001
		summarizeBy: none
		sortByColumn: Month
		sourceColumn: MonthName

	column WeekNum
		dataType: int64
		lineageTag: 54385171-7c35-0d46-5f79-289d09903de2
		summarizeBy: none
		sourceColumn: WeekNum

	partition Calendar_Full
		mode: import
		source =
			let
			    StartDate = #date(2024, 1, 1),
			    EndDate = #date(2027, 12, 31),
			    DayCount = Duration.Days(EndDate - StartDate) + 1,
			    Dates = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
			    DateTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
			    Typed = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
			    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
			    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
			    AddQuarter = Table.AddColumn(AddMonth, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
			    AddMonthName = Table.AddColumn(AddQuarter, "MonthName", each Date.ToText([Date], "MMM"), type text),
			    AddWeekNum = Table.AddColumn(AddMonthName, "WeekNum", each Date.WeekOfYear([Date], Day.Monday), Int64.Type)
			in
			    AddWeekNum
