table 'Conversion_Rate'
	lineageTag: 0b0ff5cf-bcff-e3d1-ae36-dec0bf4e9f78

	column From_Stage
		dataType: string
		lineageTag: 47b17cd2-c1bf-09be-d905-91fcf33f4552
		summarizeBy: none
		sourceColumn: From_Stage

	column To_Stage
		dataType: string
		lineageTag: 7f0fedf2-4c71-2b98-b511-725b287c40ce
		summarizeBy: none
		sourceColumn: To_Stage

	column Avg_Conv_Rate
		dataType: double
		lineageTag: f8e925df-3d20-4726-3753-63b2c15334a0
		summarizeBy: average
		sourceColumn: Avg_Conv_Rate
		formatString: 0.0%

	column Avg_Days_in_Stage
		dataType: int64
		lineageTag: a7092e1f-ba54-7966-9832-15ad1b92d726
		summarizeBy: average
		sourceColumn: Avg_Days_in_Stage

	column Stage_Sort
		dataType: int64
		lineageTag: 37d4cead-c74e-21d7-453e-121a7e302521
		summarizeBy: none
		sourceColumn: Stage_Sort

	partition Conversion_Rate = m
		mode: import
		source =
			let
				Source = Table.FromRecords(
					{
						[From_Stage = "Qualify", To_Stage = "Develop", Avg_Conv_Rate = 0.72, Avg_Days_in_Stage = 21, Stage_Sort = 1],
						[From_Stage = "Develop", To_Stage = "Validate", Avg_Conv_Rate = 0.65, Avg_Days_in_Stage = 28, Stage_Sort = 2],
						[From_Stage = "Validate", To_Stage = "Propose", Avg_Conv_Rate = 0.58, Avg_Days_in_Stage = 21, Stage_Sort = 3],
						[From_Stage = "Propose", To_Stage = "Negotiate", Avg_Conv_Rate = 0.70, Avg_Days_in_Stage = 14, Stage_Sort = 4],
						[From_Stage = "Negotiate", To_Stage = "Closed Won", Avg_Conv_Rate = 0.82, Avg_Days_in_Stage = 14, Stage_Sort = 5]
					},
					type table [
						From_Stage = text,
						To_Stage = text,
						Avg_Conv_Rate = number,
						Avg_Days_in_Stage = Int64.Type,
						Stage_Sort = Int64.Type
					]
				)
			in
				Source
