table 'Pipeline_Snapshot'
	lineageTag: fc9924ba-9841-4951-ed3b-d1eb0bd88b2f

	column Snapshot_Date
		dataType: dateTime
		lineageTag: fb189e60-78bc-9ddb-c5b8-fc145a06fc0e
		summarizeBy: none
		sourceColumn: Snapshot_Date
		formatString: yyyy-MM-dd

	column Region
		dataType: string
		lineageTag: 98411db6-983b-c7e7-3c3d-bbc3ea156dee
		summarizeBy: none
		sourceColumn: Region

	column Stage
		dataType: string
		lineageTag: 5be9fb82-eaef-f51a-9313-06567686da7d
		summarizeBy: none
		sourceColumn: Stage

	column Pipeline_ARR
		dataType: double
		lineageTag: d03197c8-b28c-a181-1744-a8bc02d06e22
		summarizeBy: sum
		sourceColumn: Pipeline_ARR
		formatString: $#,0

	column Opportunity_Count
		dataType: int64
		lineageTag: c879d564-c748-fff8-8451-8db3dc30b239
		summarizeBy: sum
		sourceColumn: Opportunity_Count

	column AKey
		dataType: string
		lineageTag: bc8f5f93-a723-8d01-093c-77fdd8faf245
		summarizeBy: none
		sourceColumn: AKey

	partition Pipeline_Snapshot
		mode: import
		source =
			let
				Source = Table.FromRecords(
					{
						[Snapshot_Date = #date(2026, 7, 6), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 18500000.0, Opportunity_Count = 42, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 6), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 12300000.0, Opportunity_Count = 31, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 6), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 9800000.0, Opportunity_Count = 25, AKey = "APJAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 13), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 18900000.0, Opportunity_Count = 44, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 13), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 12700000.0, Opportunity_Count = 33, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 13), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 10200000.0, Opportunity_Count = 26, AKey = "APJAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 20), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 19400000.0, Opportunity_Count = 45, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 20), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 13100000.0, Opportunity_Count = 34, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 20), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 10600000.0, Opportunity_Count = 27, AKey = "APJAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 27), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 20100000.0, Opportunity_Count = 47, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 27), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 13500000.0, Opportunity_Count = 35, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 7, 27), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 10900000.0, Opportunity_Count = 28, AKey = "APJAllAllAll"],
						[Snapshot_Date = #date(2026, 8, 3), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 20800000.0, Opportunity_Count = 49, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 8, 3), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 13200000.0, Opportunity_Count = 34, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 8, 3), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 11400000.0, Opportunity_Count = 29, AKey = "APJAllAllAll"],
						[Snapshot_Date = #date(2026, 9, 14), Region = "Americas", Stage = "All Stages", Pipeline_ARR = 22300000.0, Opportunity_Count = 51, AKey = "AmericasAllAllAll"],
						[Snapshot_Date = #date(2026, 9, 14), Region = "EMEA", Stage = "All Stages", Pipeline_ARR = 14600000.0, Opportunity_Count = 38, AKey = "EMEAAllAllAll"],
						[Snapshot_Date = #date(2026, 9, 14), Region = "APJ", Stage = "All Stages", Pipeline_ARR = 12300000.0, Opportunity_Count = 32, AKey = "APJAllAllAll"]
					},
					type table [
						Snapshot_Date = date,
						Region = text,
						Stage = text,
						Pipeline_ARR = number,
						Opportunity_Count = Int64.Type,
						AKey = text
					]
				)
			in
				Source
