table 'Product_Lines'
	lineageTag: 24d3e986-bce3-2965-87b0-b08075e9fcd7

	column Product_Line
		dataType: string
		lineageTag: 5a17dbcf-4375-9de6-20bb-19a5d62d3179
		summarizeBy: none
		sourceColumn: Product_Line

	column Product_Category
		dataType: string
		lineageTag: 7c5e9be9-6abc-fd2b-82b2-575df560cf82
		summarizeBy: none
		sourceColumn: Product_Category

	column ARR_Tier
		dataType: string
		lineageTag: 37da4b4d-4cfa-0812-b69b-874d0822234a
		summarizeBy: none
		sourceColumn: ARR_Tier

	column Typical_Sales_Cycle_Days
		dataType: int64
		lineageTag: 8509fd14-7af7-371d-fd76-5e74c1a65151
		summarizeBy: average
		sourceColumn: Typical_Sales_Cycle_Days

	column Product_Sort
		dataType: int64
		lineageTag: 2e0620ab-d6d6-095b-3007-39d57cba74aa
		summarizeBy: none
		sourceColumn: Product_Sort

	partition Product_Lines
		mode: import
		source =
			let
				Source = Table.FromRecords(
					{
						[Product_Line = "Data Intelligence", Product_Category = "Core Platform", ARR_Tier = "Enterprise", Typical_Sales_Cycle_Days = 180, Product_Sort = 1],
						[Product_Line = "Analytics Cloud", Product_Category = "Analytics", ARR_Tier = "Mid-Market", Typical_Sales_Cycle_Days = 120, Product_Sort = 2],
						[Product_Line = "Storage Platform", Product_Category = "Infrastructure", ARR_Tier = "Enterprise", Typical_Sales_Cycle_Days = 150, Product_Sort = 3],
						[Product_Line = "All", Product_Category = "All", ARR_Tier = "All", Typical_Sales_Cycle_Days = 0, Product_Sort = 99]
					},
					type table [
						Product_Line = text,
						Product_Category = text,
						ARR_Tier = text,
						Typical_Sales_Cycle_Days = Int64.Type,
						Product_Sort = Int64.Type
					]
				)
			in
				Source
