table 'Calendar'
	lineageTag: 5a87a4ce-a285-ee7f-543e-771571fd79f3

	column Date
		dataType: dateTime
		isHidden
		lineageTag: a7e0e13f-0540-6533-7106-a766bda9fd52
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		lineageTag: dd8318a2-334d-948d-9247-95c701b6d356
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: b0758b7c-3a9c-36bd-2463-46c6dfab789c
		summarizeBy: none
		sourceColumn: Quarter

	column Month
		dataType: int64
		lineageTag: a3871708-2ca9-26ee-7581-87eda38de2a0
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: 6f8f43ec-e063-e6ca-a0f4-295d7e072663
		summarizeBy: none
		sortByColumn: Month
		sourceColumn: MonthName

	column WeekNum
		dataType: int64
		lineageTag: 7b33ae03-a3ad-dbba-a9cc-a945a30798a6
		summarizeBy: none
		sourceColumn: WeekNum

	partition Calendar
		mode: import
		source =
			let
			    StartDate = #date(2024, 1, 1),
			    EndDate = #date(2027, 12, 31),
			    DayCount = Duration.Days(EndDate - StartDate) + 1,
			    Dates = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
			    DateTable = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
			    Typed = Table.TransformColumnTypes(DateTable, {{"Date", type date}}),
			    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
			    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
			    AddQuarter = Table.AddColumn(AddMonth, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
			    AddMonthName = Table.AddColumn(AddQuarter, "MonthName", each Date.ToText([Date], "MMM"), type text),
			    AddWeekNum = Table.AddColumn(AddMonthName, "WeekNum", each Date.WeekOfYear([Date], Day.Monday), Int64.Type)
			in
			    AddWeekNum
