"""Build the existing public URLs with the shared operating-model application."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
PAGES={
 'weekly-checkin-portal/weekly-checkin-portal.html':('wci','Forecast & Business Reviews'),
 'pipeline-pulse/pipeline-pulse.html':('pulse','Executive Pulse'),
 'funnel-management/pipeline-intelligence.html':('pipeline','Pipeline Diagnostics'),
 'net-new-tracker/net-new-tracker.html':('growth','Growth & Customer Economics'),
 'sales-league/sales-league.html':('sales','Sales Productivity & Resource Planning'),
 'data/index.html':('data','Data & Evidence'),
 'portfolio-deep-dive.html':('deep','Methodology & Evidence'),
}
for name,(module,title) in PAGES.items():
    prefix='../' if '/' in name else './'
    html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{title}. An independent commercial operations reference implementation with educational CRM data and reproducible synthetic planning scenarios.">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'">
<title>{title} | Renato Bruxel</title><link rel="stylesheet" href="{prefix}assets/gtm.css">
</head><body data-module="{module}" data-root="{prefix}"><div id="app"><main><h1>{title}</h1><p>Loading the local data bundle…</p></main></div><noscript><p>This interactive demonstration needs JavaScript. All source data, SQL and documentation are available in the <a href="{prefix}downloads/gtm-operating-system-v2.zip">downloadable package</a>.</p></noscript>
<script src="{prefix}assets/crm-data.js"></script><script src="{prefix}assets/planning-data.js"></script><script src="{prefix}assets/sql-results.js"></script><script src="{prefix}assets/gtm-model.js"></script><script src="{prefix}assets/gtm-app.js"></script></body></html>
'''
    (ROOT/name).write_text(html,encoding='utf-8')

HOME='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Renato Rodrigo Bruxel | Commercial Excellence & GTM Operations</title><meta name="description" content="Commercial Excellence and GTM Operations: three independent cases connecting forecasting, growth, resource planning and governed AI to business decisions."><link rel="stylesheet" href="assets/gtm.css"></head><body>
<a class="skip" href="#main">Skip to content</a><header class="topbar"><a class="wordmark" href="index.html">RB / Renato Rodrigo Bruxel</a><nav class="toplinks" aria-label="Portfolio"><a href="#cases">Case studies</a><a href="portfolio-deep-dive.html?tab=experience">Professional evidence</a><a href="data/index.html">Data & downloads</a></nav></header>
<main class="profile" id="main"><section class="hero"><div class="eyebrow">Commercial Excellence · GTM Strategy & Operations</div><h1>Turn commercial signals into decisions people can execute.</h1><p>I connect commercial strategy, trusted analytics, forecasting and responsible AI to improve the way teams plan, review and act.</p><div class="actions"><a class="button primary" href="#cases">Explore three case studies</a><a class="button" href="portfolio-deep-dive.html?tab=experience">My contribution & evidence</a></div><div class="facts"><div class="fact"><strong>83%</strong><span>less weekly reporting preparation</span></div><div class="fact"><strong>50%</strong><span>shorter leadership review cycle</span></div><div class="fact"><strong>~450</strong><span>sellers within quota governance scope</span></div></div><p class="small">Career outcomes supplied in my professional brief, from separate initiatives. The public demos below contain educational and synthetic data; they do not independently verify these outcomes.</p></section>
<section id="cases"><div class="eyebrow">Three decisions · five connected modules</div><div class="grid three">
<article class="panel case"><div><span class="number">01 / FORECAST OPERATING SYSTEM</span><h2>What can we commit to?</h2><p>For commercial leaders, GTM Operations and Finance. Reconcile plan, actuals and forecast; review exceptions; approve a version and track the next action.</p><p><strong>Try:</strong> compare a snapshot, save a call and export a WBR.</p></div><div class="actions"><a class="button primary" href="weekly-checkin-portal/weekly-checkin-portal.html">Run the weekly review</a><a href="pipeline-pulse/pipeline-pulse.html">Executive Pulse →</a></div></article>
<article class="panel case"><div><span class="number">02 / FUNNEL & GROWTH INTELLIGENCE</span><h2>Where should effort go next?</h2><p>For RevOps, Sales, Marketing and GTM Strategy. Separate timing changes from demand, inspect conversion cohorts and test growth and resource alternatives.</p><p><strong>Try:</strong> trace a push-out, compare acquisition economics and model capacity.</p></div><div class="actions"><a class="button primary" href="funnel-management/pipeline-intelligence.html">Diagnose the pipeline</a><a href="net-new-tracker/net-new-tracker.html">Growth & retention →</a><a href="sales-league/sales-league.html">Productivity & resources →</a></div></article>
<article class="panel case"><div><span class="number">03 / GOVERNED COMMERCIAL COPILOT</span><h2>Can we trust the answer?</h2><p>For analysts and leaders preparing commercial decisions. Retrieve shared metrics, inspect sources, test scope boundaries and retain human review.</p><p><strong>Try:</strong> ask for coverage, change the region and inspect the returned evidence.</p></div><div class="actions"><a class="button primary" href="weekly-checkin-portal/weekly-checkin-portal.html?tab=copilot">Ask the copilot</a><a href="portfolio-deep-dive.html?tab=evaluation">Evaluation results →</a></div></article>
</div></section>
<section class="grid"><div class="panel"><h2>Business judgment, with inspectable evidence</h2><p>Start from the decision, align definitions, test competing explanations and assign the follow-up. SQL and automation make that mechanism reproducible.</p><div class="section-link"><span>SQL, cohort analysis and temporal reconciliation</span><a href="portfolio-deep-dive.html?tab=sql">Inspect →</a></div><div class="section-link"><span>Workflow, roles and business-review cadence</span><a href="weekly-checkin-portal/weekly-checkin-portal.html?tab=operating">Explore →</a></div><div class="section-link"><span>Sources, contracts and quality exceptions</span><a href="data/index.html">Verify →</a></div></div><div class="panel"><h2>Reproduce the work</h2><p>The Kaggle CRM source keeps its original 2016–2017 dates. Planning, subscriptions and payments use independent deterministic scenarios. Missing facts remain visible.</p><pre class="code">python scripts/reproduce.py
python -m http.server 8000</pre><div class="actions"><a class="button primary" href="downloads/gtm-operating-system-v2.zip" download>Download code & data</a><a href="data/index.html?tab=reproduce">Read the data guide →</a></div></div></section>
<section class="panel prose"><h2>Commercial Excellence & AI/Data Transformation</h2><p>My work spans sales performance, incentive governance, forecasting, analytics, data quality and global enablement. I build operating mechanisms across teams and work hands-on with SQL, Power BI, Python, Salesforce and enterprise data platforms.</p><p>This independent implementation demonstrates analytical and operating-model patterns. It contains no employer code or records. SQLite and the browser application are tools chosen for this reference project; the local copilot is deterministic, and the role selector demonstrates scope without claiming production authorization.</p><div class="actions"><a class="button" href="https://www.linkedin.com/in/renato-rodrigo-bruxel" rel="noopener" target="_blank">LinkedIn</a><a class="button" href="mailto:renato.bruxel@hotmail.com">Contact Renato</a><a href="portfolio-deep-dive.html?tab=experience">Professional evidence & limits →</a></div></section>
<footer>Renato Rodrigo Bruxel · Blumenau, Brazil · Portfolio in English for an international audience. Source data: educational CRM (CC0); independent code and generated scenarios: MIT.</footer></main></body></html>'''
(ROOT/'index.html').write_text(HOME,encoding='utf-8')
print(f'Built {len(PAGES)+1} existing HTML URLs.')
